
security:
    providers:
        in_memory:
            memory:
              users:
                user:
                    password: user
                    roles: 'ROLE_USER'
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            form_login:
              login_path: gestion_login
              check_path: gestion_login
              default_target_path: gestion_login

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/gestion/accueil, roles: ROLE_ADMIN }
